OrdererOrgs:
    - Name: Orderer
      Domain: minvu.cl
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: Org1
      Domain: org1.minvu.cl
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org2
      Domain: org2.minvu.cl
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Org3
      Domain: org3.minvu.cl
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1