version: "2"

networks:
  basic:
services:
  int.ca.org1.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: int.ca.org1.minvu.cl
    ports:
      - "7056:7054"
    volumes:
      - ./fabric-ca/org1.minvu.cl/int:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw -u http://int.ca.org1.minvu.cl:password@root.ca.org1.minvu.cl:7054"
    networks:
      - basic

  tls.int.ca.org1.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.int.ca.org1.minvu.cl
    ports:
      - "7057:7054"
    volumes:
      - ./fabric-ca/org1.minvu.cl/tls-int:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw -u http://tls.int.ca.org1.minvu.cl:password@tls.root.ca.org1.minvu.cl:7054"
    networks:
      - basic

  int.ca.org2.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: int.ca.org2.minvu.cl
    ports:
      - "8056:7054"
    volumes:
      - ./fabric-ca/org2.minvu.cl/int:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw -u http://int.ca.org2.minvu.cl:password@root.ca.org2.minvu.cl:7054"
    networks:
      - basic

  tls.int.ca.org2.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.int.ca.org2.minvu.cl
    ports:
      - "8057:7054"
    volumes:
      - ./fabric-ca/org2.minvu.cl/tls-int:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw -u http://tls.int.ca.org2.minvu.cl:password@tls.root.ca.org2.minvu.cl:7054"
    networks:
      - basic

  int.ca.org3.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: int.ca.org3.minvu.cl
    ports:
      - "9056:7054"
    volumes:
      - ./fabric-ca/org3.minvu.cl/int:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw -u http://int.ca.org3.minvu.cl:password@root.ca.org3.minvu.cl:7054"
    networks:
      - basic

  tls.int.ca.org3.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.int.ca.org3.minvu.cl
    ports:
      - "9057:7054"
    volumes:
      - ./fabric-ca/org3.minvu.cl/tls-int:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw -u http://tls.int.ca.org3.minvu.cl:password@tls.root.ca.org3.minvu.cl:7054"
    networks:
      - basic
  #int.ca.minvu.cl:
  #  image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
  #  container_name: int.ca.minvu.cl
  #  ports:
  #    - "10056:7054"
  #  volumes:
  #    - ./fabric-ca/minvu.cl/int:/etc/hyperledger/fabric-ca-server
  #  command: >
  #    sh -c "fabric-ca-server start -b admin:adminpw -u http://int.ca.minvu.cl:password@root.ca.minvu.cl:7054"
  #  networks:
  #    - basic
  #tls.int.ca.minvu.cl:
  #  image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
  #  container_name: tls.int.ca.minvu.cl
  #  ports:
  #    - "10057:7054"
  #  volumes:
  #    - ./fabric-ca/minvu.cl/tls-int:/etc/hyperledger/fabric-ca-server
  #  command: >
  #    sh -c "fabric-ca-server start -b admin:adminpw -u http://tls.int.ca.minvu.cl:password@tls.root.ca.minvu.cl:7054"
  #  networks:
  #    - basic
