version: "2"

networks:
  basic:
services:
  # org1
  root.ca.org1.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.org1.minvu.cl
    ports:
      - "7054:7054"
    volumes:
      - ./fabric-ca/org1.minvu.cl/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  tls.root.ca.org1.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.org1.minvu.cl
    ports:
      - "7055:7054"
    volumes:
      - ./fabric-ca/org1.minvu.cl/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  # org2
  root.ca.org2.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.org2.minvu.cl
    ports:
      - "8054:7054"
    volumes:
      - ./fabric-ca/org2.minvu.cl/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  tls.root.ca.org2.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.org2.minvu.cl
    ports:
      - "8055:7054"
    volumes:
      - ./fabric-ca/org2.minvu.cl/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  # org3
  root.ca.org3.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: root.ca.org3.minvu.cl
    ports:
      - "9054:7054"
    volumes:
      - ./fabric-ca/org3.minvu.cl/root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  tls.root.ca.org3.minvu.cl:
    image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
    container_name: tls.root.ca.org3.minvu.cl
    ports:
      - "9055:7054"
    volumes:
      - ./fabric-ca/org3.minvu.cl/tls-root:/etc/hyperledger/fabric-ca-server
    command: >
      sh -c "fabric-ca-server start -b admin:adminpw"
    networks:
      - basic
  # acme
  #root.ca.minvu.cl:
  #  image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
  #  container_name: root.ca.minvu.cl
  #  ports:
  #    - "10054:7054"
  #  volumes:
  #    - ./fabric-ca/minvu.cl/root:/etc/hyperledger/fabric-ca-server
  #  command: >
  #    sh -c "fabric-ca-server start -b admin:adminpw"
  #  networks:
  #    - basic
  #tls.root.ca.minvu.cl:
  #  image: hyperledger/fabric-ca:$FABRIC_CA_IMAGE_TAG
  #  container_name: tls.root.ca.minvu.cl
  #  ports:
  #    - "10055:7054"
  #  volumes:
  #    - ./fabric-ca/minvu.cl/tls-root:/etc/hyperledger/fabric-ca-server
  #  command: >
  #    sh -c "fabric-ca-server start -b admin:adminpw"
  #  networks:
  #    - basic
