test:
  name: "Evaluación de Contratos de Postulación"
  description: "Este escenario tiene la finalidad de probar el comportamiento del método Insert"
  workers:
    type: local
    number: 3
  rounds:
    - label: Insert
      txNumber: 10
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      callback: benchmarks/callbacks/minvucontrol/postulacion/mint.js
      arguments:
        TipologiaCode: CCH
        insertedOrg: Org1
        inserted: Org1MSP
        client: client@org1.minvu.cl
        rutpostulante: 176941979
        puntaje: 99
        montosubsidiouf: 1700
        receptorOrg: Org2
        ##receptor: Org2MSP
        ##receptorClient: client@org2.minvu.cl
observer:
  type: local
  interval: 1
  #type: prometheus
  #interval: 5
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
