test:
  name: "Benchmarking de Contratos de Postulación"
  description: "Este escenario de referencia utilizará transacciones de contratos de postulación, desde la acuñación hasta la transferencia y el canje"
  workers:




    type: local
    number: 3
  rounds:
    - label: inicio
      ##txNumber: 100
      txDuration: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      callback: benchmarks/callbacks/minvucontrol/postulacion/mint.js
      arguments:
        TipologiaCode: CCH
        minterOrg: Org1
        minter: Org1MSP
        client: client@org1.minvu.cl
        receiverOrg: Org2
        receiver: Org2MSP
        receiverClient: client@org2.minvu.cl
    #- label: transfer
    #  txNumber: 500
    #  rateControl:
    #    type: fixed-rate
    #    opts:
    #      tps: 25
    #  callback: benchmarks/callbacks/foodcontrol/currency/transfer.js
    #  arguments:
    #- label: redeem
    #  txNumber: 1
    #  rateControl:
    #    type: fixed-rate
    #    opts:
    #      tps: 25
    #  callback: benchmarks/callbacks/foodcontrol/currency/redeem.js
    #  arguments:
observer:
  type: local
  interval: 1
  #type: prometheus
  #interval: 5
monitor:
  interval: 1
  type: ["docker"]
  docker:
    containers: ["all"]
  #prometheus:
  #  url: "http://prometheus:9090"
  #  push_url: "http://pushGateway:9091"
  #  metrics:
  #    ignore: [prometheus, pushGateway, cadvisor, grafana, node-exporter]
  #    include:
  #      Endorse Time (s):
  #        query: rate(endorser_propsal_duration_sum{chaincode="minvucontrol:v1.0"}[5m])/rate(endorser_propsal_duration_count{chaincode="minvucontrol:v1.0"}[5m])
  #        step: 1
  #        label: instance
  #        statistic: avg
